experiments:
  search_bar_position:
    name: Search Bar Position
    description: >
      Test if the sticky search bar creates more search queries.
    started_at: June 23, 2025 12:30 pm SGT
    ended_at: July 8, 2025 12:00 pm SGT
    variants:
      - header
      - sticky
  sort_by:
    name: Sort By Popularity
    description: >
      Test if the sort by popularity creates more event clicks.
    started_at: June 30, 2025 12:30 pm SGT
    variants:
      - time
      - popularity

exclude:
  bots: true
