experiments:
  search_bar_position:
    name: Search Bar Position
    description: >
      Test if the sticky search bar creates more search queries.
    started_at: June 23, 2025 12:30 pm SGT
    variants:
      - header
      - sticky

exclude:
  bots: true
