production:
  # find_and_create_events_job:
  #   class: Sources::FindAndCreateEventsJob
  #   schedule: "0 * * * *"  # Every hour at 0 minutes
  reindex_events_job:
    class: Events::ReindexJob
    schedule: "30 * * * *"  # Every hour at 30 minutes
