production:
  find_and_create_events_job:
    class: ScrapeAndCreateEventsJob
    schedule: "0 * * * *"  # Every hour at 0 minutes
  reindex_events_job:
    class: Events::ReindexJob
    schedule: "30 * * * *"  # Every hour at 30 minutes
  free_credits_top_up_job:
    class: Credits::FreeTopUpJob
    schedule: "0 * 1 * *"  # Every month at 00:00 on the first day of the month
